import mongoose from "mongoose";
import { startTestDb, stopTestDb, clearTestDb, oid } from "./helpers/mongo.js";

const { migrateAutoGeneratedUsernames } = await import("../src/migrations/usernames.migration.js");

const db = () => mongoose.connection.db;

const seedUser = async ({ email, username }) => {
  const user = {
    _id: oid(),
    email,
    username,
    password: "hashed-irrelevant-for-this-test",
    fullName: "Test Student",
    department: "Computer Science and Engineering",
  };
  await db().collection("users").insertOne(user);
  return user;
};

describe("Auto-generated username cleanup migration (real MongoDB)", () => {
  beforeAll(async () => {
    await startTestDb();
  }, 180000);

  afterAll(async () => {
    await stopTestDb();
  });

  beforeEach(async () => {
    await clearTestDb();
  });

  test("strips the random suffix off an untouched auto-generated username", async () => {
    console.log("[TEST] migrateAutoGeneratedUsernames › strips suffix from name.regno_abc123");
    await seedUser({ email: "krishna.20233169@mnnit.ac.in", username: "krishna.20233169_76a463" });

    const stats = await migrateAutoGeneratedUsernames(db());
    console.log(`[TEST RESULT] ${JSON.stringify(stats)}`);

    expect(stats.migrated).toBe(1);
    expect(stats.skippedCollision).toBe(0);

    const updated = await db().collection("users").findOne({ email: "krishna.20233169@mnnit.ac.in" });
    expect(updated.username).toBe("krishna.20233169");
    console.log("[TEST] Confirmed username migrated from krishna.20233169_76a463 to krishna.20233169");
  });

  test("leaves a manually customized username untouched", async () => {
    console.log("[TEST] migrateAutoGeneratedUsernames › skips a custom username");
    await seedUser({ email: "revan.20233291@mnnit.ac.in", username: "revan_the_dev" });

    const stats = await migrateAutoGeneratedUsernames(db());
    console.log(`[TEST RESULT] ${JSON.stringify(stats)}`);

    expect(stats.migrated).toBe(0);
    expect(stats.skippedNotAutoGen).toBe(1);

    const unchanged = await db().collection("users").findOne({ email: "revan.20233291@mnnit.ac.in" });
    expect(unchanged.username).toBe("revan_the_dev");
    console.log("[TEST] Confirmed custom username was left alone");
  });

  test("skips migration when the bare target username is already taken by someone else", async () => {
    console.log("[TEST] migrateAutoGeneratedUsernames › skips on collision with an existing user");
    await seedUser({ email: "tanish.20231111@mnnit.ac.in", username: "tanish.20231111_abc123" });
    // Someone else already holds the bare name (e.g. changed their username to it earlier).
    await seedUser({ email: "someoneelse.20239999@mnnit.ac.in", username: "tanish.20231111" });

    const stats = await migrateAutoGeneratedUsernames(db());
    console.log(`[TEST RESULT] ${JSON.stringify(stats)}`);

    expect(stats.migrated).toBe(0);
    expect(stats.skippedCollision).toBe(1);

    const untouched = await db().collection("users").findOne({ email: "tanish.20231111@mnnit.ac.in" });
    expect(untouched.username).toBe("tanish.20231111_abc123");
    console.log("[TEST] Confirmed the colliding account's username was left unchanged");
  });

  test("dry run reports changes without writing them", async () => {
    console.log("[TEST] migrateAutoGeneratedUsernames › dry run makes no writes");
    await seedUser({ email: "priya.20234444@mnnit.ac.in", username: "priya.20234444_def456" });

    const stats = await migrateAutoGeneratedUsernames(db(), { dryRun: true });
    console.log(`[TEST RESULT] ${JSON.stringify(stats)}`);

    expect(stats.migrated).toBe(1);

    const stillOld = await db().collection("users").findOne({ email: "priya.20234444@mnnit.ac.in" });
    expect(stillOld.username).toBe("priya.20234444_def456");
    console.log("[TEST] Confirmed dry run did not modify the database");
  });

  test("is idempotent — re-running after a successful migration finds nothing left to do", async () => {
    console.log("[TEST] migrateAutoGeneratedUsernames › idempotent on second run");
    await seedUser({ email: "arjun.20235555@mnnit.ac.in", username: "arjun.20235555_a1b2c3" });

    const firstRun = await migrateAutoGeneratedUsernames(db());
    expect(firstRun.migrated).toBe(1);

    const secondRun = await migrateAutoGeneratedUsernames(db());
    console.log(`[TEST RESULT] second run: ${JSON.stringify(secondRun)}`);

    expect(secondRun.migrated).toBe(0);
    expect(secondRun.skippedNotAutoGen).toBe(1);
    console.log("[TEST] Confirmed re-running the migration is a no-op");
  });
});
