import * as resourceRepository from "../repositories/resource.repository.js";
import { AppError } from "../utils/error.js";

export const uploadResource = async (userId, resourceData) => {
  // In a real scenario, fileUrl is generated by Cloudinary upload middleware
  if (!resourceData.title || !resourceData.fileUrl || !resourceData.branch) {
    throw new AppError("Title, file, and branch are required", 400);
  }

  return await resourceRepository.createResource({
    userId,
    title: resourceData.title,
    description: resourceData.description || "",
    resourcetags: resourceData.resourcetags || [],
    fileUrl: resourceData.fileUrl,
    fileType: resourceData.fileType,
    fileName: resourceData.fileName,
    publicId: resourceData.publicId,
    branch: resourceData.branch,
    verificationStatus: "Pending", // Automatically pending on creation
  });
};

export const getVerifiedResourcesFeed = async (cursor, limit, branchId) => {
  const resources = await resourceRepository.getVerifiedResources(cursor, parseInt(limit) || 10, branchId);
  
  const nextCursor = resources.length > 0 ? resources[resources.length - 1].createdAt : null;

  return { resources, nextCursor };
};

export const deleteResource = async (resourceId, userId, userRole) => {
  const resource = await resourceRepository.findResourceById(resourceId);
  if (!resource) {
    throw new AppError("Resource not found", 404);
  }

  // Only the owner, a moderator of the same branch, or an admin can delete the resource
  if (
    resource.userId._id.toString() !== userId.toString() &&
    userRole !== "admin" &&
    userRole !== "moderator"
  ) {
    throw new AppError("You do not have permission to delete this resource", 403);
  }

  return await resourceRepository.deleteResource(resourceId);
};
