import mongoose from "mongoose";

// ─── Message Model ──────────────────────────────────────────────────────────
const messageSchema = new mongoose.Schema(
  {
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    chat: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Chat",
      required: true,
      index: true,
    },
    content: {
      type: String,
      trim: true,
    },
    media: {
      type: String, // Cloudinary URL
    },
    mediaType: {
      type: String,
      enum: ["image", "video", "document", "audio", null],
      default: null,
    },
    // Original filename of an uploaded attachment. The stored file is renamed
    // on upload, so without this documents could only be shown as "PDF file".
    fileName: {
      type: String,
      trim: true,
      maxlength: 200,
    },
    replyTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Message",
      default: null,
    },
    readBy: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    reactions: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        emoji: {
          type: String,
          required: true,
        },
      },
    ],
    isEdited: {
      type: Boolean,
      default: false,
    },
    // "Delete for me" on someone else's message: hidden from these users only,
    // everyone else still sees it.
    hiddenFor: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    // Id generated by the sending client. Lets the client reconcile its
    // optimistic bubble with the real message (whichever of the HTTP response
    // or the socket broadcast lands first), and makes retried/double-submitted
    // sends idempotent via the unique index below.
    clientId: {
      type: String,
      trim: true,
      maxlength: 80,
    },
  },
  { timestamps: true }
);

// Ensure at least content or media is provided
messageSchema.pre("validate", function (next) {
  if (!this.content && !this.media) {
    next(new Error("Message must have either content or media"));
  } else {
    next();
  }
});

// Compound index for efficient message queries per chat and read tracking
// `_id` breaks ties for pagination: messages created in one insertMany share a
// createdAt, and a createdAt-only cursor would skip some of them at page edges.
messageSchema.index({ chat: 1, createdAt: -1, _id: -1 });
messageSchema.index(
  { sender: 1, clientId: 1 },
  { unique: true, partialFilterExpression: { clientId: { $type: "string" } } }
);
messageSchema.index({ chat: 1, readBy: 1, sender: 1 });
// Compound text index scoped by chat: a plain `{ content: "text" }` index
// means searching within ONE chat still ranks/matches against every message
// in every chat before the `chat` filter is applied. Prefixing the text index
// with `chat` lets Mongo use it to satisfy both the equality filter and the
// text search in one pass — search stays scoped to just that conversation.
messageSchema.index({ chat: 1, content: "text" });

// ─── Chat Model ─────────────────────────────────────────────────────────────
const chatSchema = new mongoose.Schema(
  {
    chatName: {
      type: String,
      trim: true,
      default: "New Chat",
    },
    isGroup: {
      type: Boolean,
      default: false,
    },
    groupImage: {
      type: String,
      default: null,
    },
    participants: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
      },
    ],
    groupAdmin: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    groupAdmins: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],
    lastMessage: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Message",
    },
    pinnedMessages: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Message",
      },
    ],
  },
  { timestamps: true }
);

// Index for fast lookup of user's chats, sorted by most recent activity
chatSchema.index({ participants: 1, updatedAt: -1, _id: -1 });

export const Chat = mongoose.model("Chat", chatSchema);
export const Message = mongoose.model("Message", messageSchema);
